export const socketVar: {
  [key: string]: number;
} = {
  /* packetOption */
  FAIL: Number(process.env.NEXT_PUBLIC_FAIL),
  SUCCESS: Number(process.env.NEXT_PUBLIC_SUCCESS),

  /* packetID */
  LOGIN_REQUEST: Number(process.env.NEXT_PUBLIC_LOGIN_REQUEST),
  LOGIN_RESPONSE: Number(process.env.NEXT_PUBLIC_LOGIN_RESPONSE),

  ROOM_MAIN_REQUEST: Number(process.env.NEXT_PUBLIC_ROOM_MAIN_REQUEST),
  ROOM_MAIN_RESPONSE: Number(process.env.NEXT_PUBLIC_ROOM_MAIN_RESPONSE),

  ROOM_CREATE_REQUEST: Number(process.env.NEXT_PUBLIC_ROOM_CREATE_REQUEST),
  ROOM_CREATE_RESPONSE: Number(process.env.NEXT_PUBLIC_ROOM_CREATE_RESPONSE),

  ROOM_ENTER_REQUEST: Number(process.env.NEXT_PUBLIC_ROOM_ENTER_REQUEST),
  ROOM_ENTER_RESPONSE: Number(process.env.NEXT_PUBLIC_ROOM_ENTER_RESPONSE),

  ROOM_INFO_REQUEST: Number(process.env.NEXT_PUBLIC_ROOM_INFO_REQUEST),
  ROOM_INFO_RESPONSE: Number(process.env.NEXT_PUBLIC_ROOM_INFO_RESPONSE),

  ROOM_EXIT_REQUEST: Number(process.env.NEXT_PUBLIC_ROOM_EXIT_REQUEST),
  ROOM_EXIT_RESPONSE: Number(process.env.NEXT_PUBLIC_ROOM_EXIT_RESPONSE),

  ROOM_KICKOUT_REQUEST: Number(process.env.NEXT_PUBLIC_ROOM_KICKOUT_REQUEST),
  ROOM_KICKOUT_RESPONSE: Number(process.env.NEXT_PUBLIC_ROOM_KICKOUT_RESPONSE),

  ROOM_SEARCH_REQUEST: Number(process.env.NEXT_PUBLIC_ROOM_SEARCH_REQUEST),
  ROOM_SEARCH_RESPONSE: Number(process.env.NEXT_PUBLIC_ROOM_SEARCH_RESPONSE),

  ROOM_READY_REQUEST: Number(process.env.NEXT_PUBLIC_ROOM_READY_REQUEST),
  ROOM_READY_RESPONSE: Number(process.env.NEXT_PUBLIC_ROOM_READY_RESPONSE),

  R_ROOM_LIST_RESPONSE: Number(process.env.NEXT_PUBLIC_R_ROOM_LIST_RESPONSE),
  R_ROOM_INFO_RESPONSE: Number(process.env.NEXT_PUBLIC_R_ROOM_INFO_RESPONSE),
  R_ROOM_EXIT_RESPONSE: Number(process.env.NEXT_PUBLIC_R_ROOM_EXIT_RESPONSE),

  GAME_PUT_REQUEST: Number(process.env.NEXT_PUBLIC_GAME_PUT_REQUEST),
  GAME_PUT_RESPONSE: Number(process.env.NEXT_PUBLIC_GAME_PUT_RESPONSE),

  GAME_GIVEUP_REQUEST: Number(process.env.NEXT_PUBLIC_GAME_GIVEUP_REQUEST),
  GAME_GIVEUP_RESPONSE: Number(process.env.NEXT_PUBLIC_GAME_GIVEUP_RESPONSE),

  R_GAME_START_RESPONSE: Number(process.env.NEXT_PUBLIC_R_GAME_START_RESPONSE),
  R_GAME_PUT_RESPONSE: Number(process.env.NEXT_PUBLIC_R_GAME_PUT_RESPONSE),
  R_GAME_TURN_RESPONSE: Number(process.env.NEXT_PUBLIC_R_GAME_TURN_RESPONSE),
  R_GAME_RESULT_RESPONSE: Number(
    process.env.NEXT_PUBLIC_R_GAME_RESULT_RESPONSE
  ),
};
